### PR TITLE
fix parameter contentId block content

### PR DESCRIPTION
**Pull request by itkg-alavieille**

### CODE REVIEW

**Comment by nicolasThal** [comment]
Why did you put a separation between Master and Current request ?

**Comment by itkg-alavieille** [comment]
i use the master request for the context and preview because the parameter isn't in the block content parameter strategy . I can add it in strategie but the token parameter is just for the context bo.

**Comment by nicolasThal** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
:+1:

**Pull request merged**
